### ISSUE TITLE
Don't run on Ubuntu 17.04 with python3

### ISSUE THREAD

**Issue by s17t** [johncf/java-play2#1]
Hello, I'm not a Python expert. After follow the README instruction I get this error:

```
raise ImportError("No module named %r" % name)
ImportError: No module named 'asyncio.base_futures'
```

I am using python3 interpreter. Any help ? Thank you !

```bash
$ python3 --versione 3.5.3
```

**Comment by johncf** [comment]
Complete backtrace?

`asyncio` is not used directly from this project. It's probably a dependency listing bug in one of this project's dependency. You could try installing `asyncio`:

    # pip3 install asyncio
